var goods = {
  category: [
    {
      gtId: 0,
      gtName: '本店推荐',
    },
    {
      gtId: 1,
      gtName: '人气推荐',
    },
    {
      gtId: 2,
      gtName: '干锅类',
    },
    {
      gtId: 3,
      gtName: '火锅类',
    },
    {
      gtId: 4,
      gtName: '酒水',
    }, 
  ],
	product: [
    {
      goodsId: 0,
      goodsName: '什锦葛仙米',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/5.png",
      goodsType: 0,
      num: 0,    
      goodsUnit: '盘',
      huobao:1,
      tuijian:0,
      red: true,
    },
    {
      goodsId: 1,
      goodsName: '火烧茨菰',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/6.png",
      goodsType: 0,
      num: 0,
      commons: "主料:炒玉米胡萝卜",
      goodsUnit: '盘',
      huobao: 2,
      tuijian: 1,
      red: true,
    },
    {
      goodsId: 2,
      goodsName: '麻辣野鸡',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/7.png",
      goodsType: 0,
      num: 0,
      goodsUnit: '盘',
      huobao: 3,
      tuijian: 0,
      red: true,
    },
    {
      goodsId: 3,
      goodsName: '咸肉丝儿',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/8.png",
      goodsType: 0,
      num: 0,
      commons: "主料:炒玉米胡萝卜",
      goodsUnit: '盘',
      huobao: 4,
      tuijian: 1,
    },
    {
      goodsId: 4,
      goodsName: '清焖莲子',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/9.png",
      goodsType: 0,
      num: 0,
      goodsUnit: '盘',
      huobao: 5,
      tuijian: 0,
    },
    {
      goodsId: 5,
      goodsName: '黄鱼锅子',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/10.png",
      goodsType: 0,
      num: 0,
      commons: "主料:炒玉米胡萝卜",
      goodsUnit: '盘',
      huobao: 2,
      tuijian: 1,
    },
    {
      goodsId: 6,
      goodsName: '扒鸡腿儿',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/11.png",
      goodsType: 0,
      num: 0,
      goodsUnit: '盘',
      huobao: 3,
      tuijian: 0,
    },
    {
      goodsId: 7,
      goodsName: '糖焖莲子',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/12.png",
      goodsType: 0,
      num: 0,
      commons: "主料:炒玉米胡萝卜",
      goodsUnit: '盘',
      huobao: 5,
      tuijian: 1,
    }, {
      goodsId: 8,
      goodsName: '白菜锅子',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/13.png",
      goodsType: 0,
      num: 0,
      goodsUnit: '盘',
      huobao: 3,
      tuijian: 0,
    }, {
      goodsId: 9,
      goodsName: '八宝榛子酱',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/14.png",
      goodsType: 0,
      num: 0,
      goodsUnit: '盘',
      huobao: 1,
      tuijian: 0,
    },
    {
      goodsId: 10,
      goodsName: '八宝榛子酱',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/9.png",
      goodsType: 1,
      num: 0,
      commons: "主料:炒玉米胡萝卜",
      goodsUnit: '盘',
      huobao: 4,
      tuijian: 1,
    },
    {
      goodsId: 11,
      goodsName: '佛手海参',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/16.png",
      goodsType: 1,
      num: 0,
      goodsUnit: '盘',
      huobao: 2,
      tuijian: 0,
    },
    {
      goodsId: 12,
      goodsName: '素炝春不老',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/17.png",
      goodsType: 1,
      num: 0,
      commons: "主料:炒玉米胡萝卜",
      goodsUnit: '盘',
      huobao: 4,
      tuijian: 1,
    },
    {
      goodsId: 13,
      goodsName: '炸鹿尾儿',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/18.png",
      goodsType: 2,
      num: 0,
      goodsUnit: '盘',
      huobao: 5,
      tuijian: 0,
    },
    {
      goodsId: 14,
      goodsName: '扒带鱼',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/19.png",
      goodsType: 2,
      num: 0,
      commons: "主料:炒玉米胡萝卜",
      goodsUnit: '盘',
      huobao: 2,
      tuijian: 1,
    },
    {
      goodsId: 15,
      goodsName: '酿山药',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/20.png",
      goodsType: 2,
      num: 0,
      goodsUnit: '盘',
      huobao: 3,
      tuijian: 0,
    },
    {
      goodsId: 16,
      goodsName: '拔丝山药',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/21.png",
      goodsType: 3,
      num: 0,
      commons: "主料:炒玉米胡萝卜",
      goodsUnit: '盘',
      huobao: 2,
      tuijian: 1,
    },

    {
      goodsId: 17,
      goodsName: '小炒螃蟹',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/22.png",
      goodsType: 3,
      num: 0,
      goodsUnit: '盘',
      huobao: 3,
      tuijian: 0,
    },
    {
      goodsId: 18,
      goodsName: '烩腰丁儿',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/23.png",
      goodsType: 3,
      num: 0,
      goodsUnit: '盘',
      huobao: 4,
      tuijian: 0,
    },
    {
      goodsId: 19,
      goodsName: '拌皮渣儿',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/24.png",
      goodsType: 4,
      num: 0,
      goodsUnit: '盘',
      huobao: 2,
      tuijian: 0,
    },
    {
      goodsId: 20,
      goodsName: '咸肉丝儿',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/25.png",
      goodsType: 4,
      num: 0,
      commons: "主料:炒玉米胡萝卜",
      goodsUnit: '盘',
      huobao: 3,
      tuijian: 1,
    },
    {
      goodsId: 21,
      goodsName: '炒银枝儿',
      goodsEnName: 'EnglishName',
      goodsXj: 38,
      goodsImg: "../../images/6.png",
      goodsType: 4,
      num: 0,
      goodsUnit: '盘',
      huobao: 2,
      tuijian: 0,
    },
  ]
}


module.exports = {
  js_cate: goods,
}